### ISSUE TITLE
missing values in prediction with `survival_reg(engine = "flexsurv")`

### ISSUE THREAD

**Issue by hfrick** [tidymodels/censored#152] opened 2022-02-03 15:27 UTC
The error coming from flexsurv is [fixed](https://github.com/chjackson/flexsurv-dev/commit/bf7a19bd2a91e426fca707858768786492f2d3e5) in the dev version. Todo for censored: switch from `summary.flexsurvreg()` to `predict.flexsurvreg()` (also for other types of prediction).

``` r
library(censored)
#> Loading required package: parsnip
#> Loading required package: survival

lung_train <- lung[-c(1:5), ]
lung_test <- lung[13:15, ]

# contains NA
lung_test$ph.ecog
#> [1]  1 NA  1

sr_spec <-
  survival_reg(dist = "weibull") %>%
  set_engine("flexsurv") %>%
  set_mode("censored regression")
sr_fit <- sr_spec %>%
  fit(Surv(time, status) ~ ph.ecog, data = lung_train)

predict(sr_fit, lung_test, type = "hazard", time = c(100, 500, 1000)) 
#> Error in if (any(scale < 0)) {: missing value where TRUE/FALSE needed
```

<sup>Created on 2022-02-03 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by mattwarkentin** [comment] 2022-02-09 20:45
Hi @hfrick,

I think some of the predictions for `flexsurv` models have been broke due to a massive rewrite of `summary.flexsurvreg`. I am going to try and fix with a PR on that side of things, and then a fix on this side should be easier.

**Comment by mattwarkentin** [comment] 2022-02-09 23:24
PR has been submitted over at `{flexsurv}` to fix `predict.flexsurvreg` and improve the test coverage substantially. If/when it is merged it should hopefully simplify things over here, too.

**Comment by hfrick** [comment] 2022-02-10 09:36
Awesome, thank you! 🙏 I'll wait with this one until your changes to flexsurv are in

**Comment by mattwarkentin** [comment] 2022-02-15 19:17
Ah yes, I see this slipped past my test coverage. I will await Chris's response and will update `predict.flexsurvreg` and the accompanying tests to .

> Would you be open to changing that in flexsurv?

I would definitely be open to this change. Once the missing data issue is sorted out I will propose this change and work on a PR to implement it.

**Comment by hfrick** [comment] 2022-02-16 10:24
That's awesome, thank you! 🙌 Chris was really fast with fixing the issue I opened, too!

**Comment by hfrick** [comment] 2022-02-16 15:59
Sure thing! If we don't need to nest anything, we call the column `.pred_<type>`, so e.g., `.pred_time` or `.pred_linear_pred`.  If we need to nest, the "top level" column name is `.pred`, and `.pred_<type>` is used in the nested tibble. We currently do that for the prediction types `survival`, `hazard`, and `quantile`. The nested tibble also contains a `.time` column for `survival` and `hazard`, and a `.quantile` column for quantile predictions. You can see all those for the `flexsurv` engine in the [article with examples](https://censored.tidymodels.org/articles/examples.html#survival_reg-models).

Confidence intervals are added as columns `.pred_lower` and `.pred_upper`, for examples see the PRs linked in #134.

I don't think censored currently adds the standard error but given from what I see in parsnip I think that this will result in a column named `.std_error`.

**Comment by mattwarkentin** [comment] 2022-02-23 18:29
Okay, I think we are all good as of https://github.com/chjackson/flexsurv-dev/pull/122 and 9b64de986f4f50ee84fbf220605fa5c48a199e47

**Comment by hfrick** [comment] 2022-02-28 15:40
Thanks so much @mattwarkentin! I'll get this probably early next week

**Comment by mattwarkentin** [comment] 2022-03-01 15:34
No problem - happy to help. Please do let me know if you find any issues or friction points.

**Comment by hfrick** [comment] 2022-03-23 10:40
@mattwarkentin I've switched censored over to the dev version of flexsurv to make of that shiny new `predict()` ✨ 

I noticed two things: 
* Getting the survival probability and hazard at `times = 0` is not permitted for `predict()` while it is for `summary()`. Is that intentional?
* The class of the nested column of the prediction data frame is a vctrs list while ours is typically just a plain list. Just wanted to flag that in case you're doing something more complicated than you need to.

``` r
library(flexsurv)
#> Loading required package: survival

mod <- flexsurvreg(Surv(time, status) ~ age + sex, data = lung, dist = "weibull")

# can't use time = 0 for `predict()` but possible for `summary()`
predict(mod, head(lung), type = "survival", times = c(0, 500, 1000))
#> Error: `times` must be a vector of positive real-valued numbers.
summary(mod, head(lung), type = "survival", t = c(0, 500, 1000))
#> age=74,sex=1 
#>   time         est         lcl        ucl
#> 1    0 1.000000000 1.000000000 1.00000000
#> 2  500 0.156925422 0.091666643 0.24338298
#> 3 1000 0.009623031 0.001907717 0.03158447
#> 4    0 1.000000000 1.000000000 1.00000000
#> 5  500 0.156925422 0.091666643 0.24338298
#> 6 1000 0.009623031 0.001907717 0.03158447
#> 
#> age=68,sex=1 
#>   time        est       lcl        ucl
#> 1    0 1.00000000 1.0000000 1.00000000
#> 2  500 0.18639445 0.1266548 0.25526009
#> 3 1000 0.01481533 0.0043408 0.03678315
#> 
#> age=56,sex=1 
#>   time        est         lcl        ucl
#> 1    0 1.00000000 1.000000000 1.00000000
#> 2  500 0.25102807 0.172038240 0.33652372
#> 3 1000 0.03125262 0.009543035 0.06834076
#> 
#> age=57,sex=1 
#>   time        est         lcl        ucl
#> 1    0 1.00000000 1.000000000 1.00000000
#> 2  500 0.24540596 0.169718386 0.32680362
#> 3 1000 0.02952712 0.009318406 0.06353374
#> 
#> age=60,sex=1 
#>   time        est         lcl        ucl
#> 1    0 1.00000000 1.000000000 1.00000000
#> 2  500 0.22876821 0.161877403 0.29834181
#> 3 1000 0.02476127 0.008328376 0.05163929

# without times = 0
pred <- predict(mod, head(lung), type = "survival", times = c(500, 1000))
pred
#> # A tibble: 6 × 1
#>                .pred
#>   <list<tibble[,2]>>
#> 1            [2 × 2]
#> 2            [2 × 2]
#> 3            [2 × 2]
#> 4            [2 × 2]
#> 5            [2 × 2]
#> 6            [2 × 2]

# why this class?
class(pred$.pred)
#> [1] "vctrs_list_of" "vctrs_vctr"    "list"
```

<sup>Created on 2022-03-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Closed** 2022-03-23 10:48 UTC
Labels: bug

**Comment by mattwarkentin** [comment] 2022-03-23 15:14
> Getting the survival probability and hazard at `times = 0` is not permitted for `predict()` while it is for `summary()`. Is that intentional?

Good catch! This is just an oversight on my behalf. It should definitely be permitted.

> The class of the nested column of the prediction data frame is a vctrs list while ours is typically just a plain list. Just wanted to flag that in case you're doing something more complicated than you need to.

Hmm, indeed. Turns out this was being caused by `dplyr::group_nest()`. That function is listed as experimental so probably best not to use it anyway. I have switched to using the canonical `tidyr::nest()`, which returns standard list-columns (i.e. class `list`).

I have made these changes in my fork - I will push a PR shortly for Chris to review and merge. Thanks for letting me know!

**Comment by hfrick** [comment] 2022-03-23 15:17
Awesome, thank you! 🙌

**Comment by mattwarkentin** [comment] 2022-03-24 17:46
Fixed with https://github.com/chjackson/flexsurv-dev/pull/126
